sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

branches:
  only:
  - release

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

deploy:
  provider: pages
  edge: true # opt in to dpl v2
  local-dir: ./site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  github-token: $GITHUB_TOKEN
  on:
    branch: release
